version: "3.7"
x-common-variables: &common-variables
  NODE_ENV: local
  DB_MAIN_HOST: mysql
  DB_MAIN_USER: root
  DB_MAIN_PASS: root
  DB_MAIN_NAME: main_db
  AWS_ACCESS_KEY_ID: anykey
  AWS_SECRET_ACCESS_KEY: anysecret
  AWS_DEFAULT_REGION: us-east-2
services:
  local:
    build:
      context: .
    image: supermercado-backend
    volumes:
      - ./src:/app/src
    container_name: supermercado-backend_local
    environment: *common-variables
    depends_on:
      - mysql
    ports:
      - "3000:3000"
      - "9229:9229"
    tty: true
    entrypoint: ["npm", "run", "local"]
  localstack:
    image: localstack/localstack:0.11.4
    container_name: notifications-component_localstack
    environment:
      SERVICES: sqs,sns,dynamodb
      DEFAULT_REGION: us-east-2
    ports:
      - 8070:8080
      - 4576:4576
      - 4575:4575
      - "4569:4569"
  setup:
    image: mesosphere/aws-cli
    container_name: notifications-component_setup
    volumes:
      - ./scripts/local:/setup
    environment:
      AWS_ACCESS_KEY_ID: anykey
      AWS_SECRET_ACCESS_KEY: anysecret
      AWS_DEFAULT_REGION: us-east-2
    depends_on:
      - localstack
    entrypoint: [""]
    command: ["/setup/setup.sh"]
  test:
    build:
      context: .
    image: supermercado-backend
    volumes:
      - ./src:/app/src
      - ./coverage/unit:/app/coverage
    container_name: supermercado-backend_test
    environment: *common-variables
    tty: true
    entrypoint: ["npm", "test"]
  integration-test:
    build:
      context: .
    image: supermercado-backend
    volumes:
      - ./src:/app/src
      - ./coverage/integration:/app/coverage
    container_name: supermercado-backend_integration
    environment:
      <<: *common-variables
      NODE_ENV: test
    depends_on:
      - mysql
    tty: true
    entrypoint: ["npm", "run", "integration"]
  mysql:
    image: mysql:5.7
    container_name: supermercado-database_mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/schema-test.sql:/docker-entrypoint-initdb.d/schema-test.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: testpass
networks:
  default:
    name: supermercado-backend
